<?php


namespace App\GraphQL;


use App\Models\QuizAnswer;
use App\Shared\GraphqlResolver;
use Illuminate\Database\Eloquent\Model;

class QuizAnswerResolver extends GraphqlResolver
{

  public function getExcluded(array $array): array
  {
    return [];
  }

  public function makeModel(): Model
  {
    return QuizAnswer::create($this->modelArguments);
  }
  protected function transformArguments(array $arguments)
  {
    $arguments['meta_data'] = json_encode($arguments['meta_data']);
    return parent::transformArguments($arguments); // TODO: Change the autogenerated stub
  }
}
